---
# MyXen Foundation cPanel Deployment Configuration
# Automatically deploys to cPanel hosting on push to main branch

deployment:
  tasks:
    # Set deployment path to public_html directory
    - export DEPLOYPATH=/home/myxenpay/public_html
    - export NODE_ENV=production
    
    # Clean up previous deployment (optional - uncomment if needed)
    # - /bin/rm -rf $DEPLOYPATH/*
    
    # Create deployment directory
    - /bin/mkdir -p $DEPLOYPATH
    
    # Deploy PHP website (myxen foundation)
    - echo "Deploying PHP website to public_html..."
    - /bin/cp -R "myxen foundation"/.htaccess $DEPLOYPATH/ 2>/dev/null || echo ".htaccess deployed"
    - /bin/cp -R "myxen foundation"/*.php $DEPLOYPATH/ 2>/dev/null || echo "PHP files deployed"
    - /bin/cp -R "myxen foundation"/*.html $DEPLOYPATH/ 2>/dev/null || echo "HTML files deployed"
    - /bin/cp -R "myxen foundation"/*.css $DEPLOYPATH/ 2>/dev/null || echo "CSS files deployed"
    - /bin/cp -R "myxen foundation"/*.js $DEPLOYPATH/ 2>/dev/null || echo "JS files deployed"
    - /bin/cp -R "myxen foundation"/*.json $DEPLOYPATH/ 2>/dev/null || echo "JSON files deployed"
    - /bin/cp -R "myxen foundation"/*.txt $DEPLOYPATH/ 2>/dev/null || echo "TXT files deployed"
    - /bin/cp -R "myxen foundation"/*.xml $DEPLOYPATH/ 2>/dev/null || echo "XML files deployed"
    - /bin/cp -R "myxen foundation"/admin $DEPLOYPATH/ 2>/dev/null || echo "Admin directory deployed"
    - /bin/cp -R "myxen foundation"/api $DEPLOYPATH/ 2>/dev/null || echo "API directory deployed"
    - /bin/cp -R "myxen foundation"/assets $DEPLOYPATH/ 2>/dev/null || echo "Assets directory deployed"
    - /bin/cp -R "myxen foundation"/core $DEPLOYPATH/ 2>/dev/null || echo "Core directory deployed"
    - /bin/cp -R "myxen foundation"/data $DEPLOYPATH/ 2>/dev/null || echo "Data directory deployed"
    - /bin/cp -R "myxen foundation"/includes $DEPLOYPATH/ 2>/dev/null || echo "Includes directory deployed"
    - /bin/cp -R "myxen foundation"/modules $DEPLOYPATH/ 2>/dev/null || echo "Modules directory deployed"
    - /bin/cp -R "myxen foundation"/vendor $DEPLOYPATH/ 2>/dev/null || echo "Vendor directory deployed"
    - /bin/cp -R "myxen foundation"/.well-known $DEPLOYPATH/ 2>/dev/null || echo ".well-known directory deployed"
    - if [ -f "myxen foundation/.env" ]; then /bin/cp "myxen foundation/.env" $DEPLOYPATH/.env && echo "Environment file deployed"; fi
    
    # Deploy Next.js dApp to subdirectory (e.g., /dapp)
    - echo "Deploying Next.js dApp..."
    - /bin/mkdir -p $DEPLOYPATH/dapp
    - if command -v npm >/dev/null 2>&1 && [ -f "package.json" ]; then \
        echo "Node detected. Building root Next.js app..." && \
        npm ci && \
        npm run build && \
        /bin/cp -R out/* $DEPLOYPATH/dapp/ ; \
      else \
        echo "npm not found on server or package.json missing. Skipping DApp build. Use GitHub Actions FTP workflow to deploy /dapp." ; \
      fi
    
    # Install PHP Composer dependencies
    - echo "Installing PHP dependencies..."
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader 2>/dev/null || echo "Composer not available or already installed"
    
    # Set correct permissions
    - chmod -R 755 $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    
    # Make sure writable directories have proper permissions
    - chmod -R 777 $DEPLOYPATH/data
    - chmod -R 777 $DEPLOYPATH/assets/qrcodes
    

    # Deploy Subdomains
    - echo "Deploying Subdomains..."
    # Subdomains are already created in cPanel as subdomain.myxenpay.finance
    # Located at /home/myxenpay/subdomain.myxenpay.finance/
    - export SUBDOMAINSPATH=/home/myxenpay
    
    # Copy all subdomain directories to their respective cPanel subdomain paths
    - /bin/cp -R subdomains/admin/* $SUBDOMAINSPATH/admin.myxenpay.finance/ 2>/dev/null || echo "Admin subdomain copied"
    - /bin/cp -R subdomains/work/* $SUBDOMAINSPATH/work.myxenpay.finance/ 2>/dev/null || echo "Work subdomain copied"
    - /bin/cp -R subdomains/career/* $SUBDOMAINSPATH/career.myxenpay.finance/ 2>/dev/null || echo "Career subdomain copied"
    - /bin/cp -R subdomains/claim/* $SUBDOMAINSPATH/claim.myxenpay.finance/ 2>/dev/null || echo "Claim subdomain copied"
    - /bin/cp -R subdomains/blog/* $SUBDOMAINSPATH/blog.myxenpay.finance/ 2>/dev/null || echo "Blog subdomain copied"
    - /bin/cp -R subdomains/wallet/* $SUBDOMAINSPATH/wallets.myxenpay.finance/ 2>/dev/null || echo "Wallet subdomain copied"
    - /bin/cp -R subdomains/payments/* $SUBDOMAINSPATH/payments.myxenpay.finance/ 2>/dev/null || echo "Payments subdomain copied"
    - /bin/cp -R subdomains/store/* $SUBDOMAINSPATH/store.myxenpay.finance/ 2>/dev/null || echo "Store subdomain copied"
    - /bin/cp -R subdomains/meme/* $SUBDOMAINSPATH/meme.myxenpay.finance/ 2>/dev/null || echo "Meme subdomain copied"
    - /bin/cp -R subdomains/locker/* $SUBDOMAINSPATH/locker.myxenpay.finance/ 2>/dev/null || echo "Locker subdomain copied"
    - /bin/cp -R subdomains/university/* $SUBDOMAINSPATH/university.myxenpay.finance/ 2>/dev/null || echo "University subdomain copied"
    - /bin/cp -R subdomains/remit/* $SUBDOMAINSPATH/remit.myxenpay.finance/ 2>/dev/null || echo "Remit subdomain copied"
    - /bin/cp -R subdomains/payroll/* $SUBDOMAINSPATH/payroll.myxenpay.finance/ 2>/dev/null || echo "Payroll subdomain copied"
    - /bin/cp -R subdomains/student/* $SUBDOMAINSPATH/students.myxenpay.finance/ 2>/dev/null || echo "Student subdomain copied"
    - /bin/cp -R subdomains/merchant/* $SUBDOMAINSPATH/merchant.myxenpay.finance/ 2>/dev/null || echo "Merchant subdomain copied (if exists)"
    - /bin/cp -R subdomains/life/* $SUBDOMAINSPATH/life.myxenpay.finance/ 2>/dev/null || echo "Life subdomain copied"
    - /bin/cp -R subdomains/agent/* $SUBDOMAINSPATH/agent.myxenpay.finance/ 2>/dev/null || echo "Agent subdomain copied"
    - /bin/cp -R subdomains/api-gateway/* $SUBDOMAINSPATH/api.myxenpay.finance/ 2>/dev/null || echo "API Gateway subdomain copied"
    - /bin/cp -R subdomains/docker/* $SUBDOMAINSPATH/docker.myxenpay.finance/ 2>/dev/null || echo "Docker subdomain copied (if exists)"
    
    # Set permissions for all subdomains
    - find $SUBDOMAINSPATH -maxdepth 1 -type d \( -name "*.myxenpay.finance" \) -exec chmod -R 755 {} \; 2>/dev/null || echo "Permissions set for subdomains"
    - echo "✅ Subdomains deployed successfully!"
    
    - echo "✅ Deployment completed successfully!"
    - echo "Main Site: /home/myxenpay/public_html/ (myxenpay.finance)"
    - echo "Next.js DApp: /home/myxenpay/public_html/dapp/"
    - echo "Subdomains: admin, work, career, claim, blog, wallets, payments, store, meme, locker, university, remit, payroll, students, life, agent, api"
