---
# MyXen Foundation cPanel Deployment Configuration
# Automatically deploys to cPanel hosting on push to main branch

deployment:
  tasks:
    # Set deployment path to studyproglobal.com.bd directory
    - export DEPLOYPATH=/home/studyproglobal.com.bd
    - export BACKENDPATH=/home/studyproglobal.com.bd/studypro-backend
    - export NODE_ENV=production
    
    # Clean up previous deployment (optional - uncomment if needed)
    # - /bin/rm -rf $DEPLOYPATH/*
    
    # Create deployment directory
    - /bin/mkdir -p $DEPLOYPATH
    
    # Deploy PHP website (myxen foundation)
    - echo "Deploying PHP website..."
    - /bin/cp -R "myxen foundation"/.htaccess $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.php $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.html $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.css $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.js $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.json $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.txt $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/*.xml $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/admin $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/api $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/assets $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/core $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/data $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/includes $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/modules $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/vendor $DEPLOYPATH/
    - /bin/cp -R "myxen foundation"/.well-known $DEPLOYPATH/
    
    # Install PHP Composer dependencies
    - echo "Installing PHP dependencies..."
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader 2>/dev/null || echo "Composer not available or already installed"
    
    # Deploy Next.js dApp to subdirectory (e.g., /dapp)
    - echo "Deploying Next.js dApp..."
    - /bin/mkdir -p $DEPLOYPATH/dapp
    - if command -v npm >/dev/null 2>&1; then \
        echo "Node detected. Building root Next.js app..." && \
        npm ci && \
        npm run build && \
        /bin/cp -R out/* $DEPLOYPATH/dapp/ ; \
      else \
        echo "npm not found on server. Skipping DApp build. Use GitHub Actions FTP workflow to deploy /dapp." ; \
      fi
    
    # Set correct permissions
    - chmod -R 755 $DEPLOYPATH
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    
    # Make sure writable directories have proper permissions
    - chmod -R 777 $DEPLOYPATH/data
    - chmod -R 777 $DEPLOYPATH/assets/qrcodes
    
    # Deploy Backend files (if backend directory exists)
    - echo "Deploying Backend files..."
    - /bin/mkdir -p $BACKENDPATH
    - if [ -d "backend" ]; then \
        /bin/cp -R backend/* $BACKENDPATH/ ; \
        chmod -R 755 $BACKENDPATH ; \
        find $BACKENDPATH -type f -exec chmod 644 {} \; ; \
        find $BACKENDPATH -type d -exec chmod 755 {} \; ; \
        echo "Backend deployed to $BACKENDPATH" ; \
      else \
        echo "No backend directory found, skipping backend deployment" ; \
      fi
    
    # Deploy Subdomains
    - echo "Deploying Subdomains..."
    - export SUBDOMAINSPATH=/home/studyproglobal.com.bd
    - /bin/cp -R subdomains/admin $SUBDOMAINSPATH/admin 2>/dev/null || echo "Admin subdomain copied"
    - /bin/cp -R subdomains/work $SUBDOMAINSPATH/work 2>/dev/null || echo "Work subdomain copied"
    - /bin/cp -R subdomains/career $SUBDOMAINSPATH/career 2>/dev/null || echo "Career subdomain copied"
    - /bin/cp -R subdomains/claim $SUBDOMAINSPATH/claim 2>/dev/null || echo "Claim subdomain copied"
    - /bin/cp -R subdomains/blog $SUBDOMAINSPATH/blog 2>/dev/null || echo "Blog subdomain copied"
    - /bin/cp -R subdomains/wallet $SUBDOMAINSPATH/wallet 2>/dev/null || echo "Wallet subdomain copied"
    - /bin/cp -R subdomains/payments $SUBDOMAINSPATH/payments 2>/dev/null || echo "Payments subdomain copied"
    - /bin/cp -R subdomains/store $SUBDOMAINSPATH/store 2>/dev/null || echo "Store subdomain copied"
    - /bin/cp -R subdomains/meme $SUBDOMAINSPATH/meme 2>/dev/null || echo "Meme subdomain copied"
    - /bin/cp -R subdomains/locker $SUBDOMAINSPATH/locker 2>/dev/null || echo "Locker subdomain copied"
    - /bin/cp -R subdomains/university $SUBDOMAINSPATH/university 2>/dev/null || echo "University subdomain copied"
    - /bin/cp -R subdomains/remit $SUBDOMAINSPATH/remit 2>/dev/null || echo "Remit subdomain copied"
    - /bin/cp -R subdomains/payroll $SUBDOMAINSPATH/payroll 2>/dev/null || echo "Payroll subdomain copied"
    - /bin/cp -R subdomains/student $SUBDOMAINSPATH/student 2>/dev/null || echo "Student subdomain copied"
    - /bin/cp -R subdomains/merchant $SUBDOMAINSPATH/merchant 2>/dev/null || echo "Merchant subdomain copied"
    - /bin/cp -R subdomains/life $SUBDOMAINSPATH/life 2>/dev/null || echo "Life subdomain copied"
    - chmod -R 755 $SUBDOMAINSPATH/admin $SUBDOMAINSPATH/work $SUBDOMAINSPATH/career $SUBDOMAINSPATH/claim $SUBDOMAINSPATH/blog $SUBDOMAINSPATH/wallet $SUBDOMAINSPATH/payments $SUBDOMAINSPATH/store $SUBDOMAINSPATH/meme $SUBDOMAINSPATH/locker $SUBDOMAINSPATH/university $SUBDOMAINSPATH/remit $SUBDOMAINSPATH/payroll $SUBDOMAINSPATH/student $SUBDOMAINSPATH/merchant $SUBDOMAINSPATH/life 2>/dev/null || echo "Permissions set for subdomains"
    - echo "✅ Subdomains deployed successfully!"
    
    - echo "✅ Deployment completed successfully!"
    - echo "Frontend: /home/studyproglobal.com.bd/"
    - echo "Backend: /home/studyproglobal.com.bd/studypro-backend/"
    - echo "Subdomains: admin, work, career, claim, blog, wallet, payments, store, meme, locker, university, remit, payroll, student, merchant, life"
